

### Get all fragrances
GET http://localhost:8081/api/fragrances

###
POST http://localhost:8081/api/fragrances
Content-Type: application/json

{
  "name": "Dior Sauvage",
  "brand": "Dior",
  "gender": "Men",
  "year": 2015,
  "notes": ["Bergamot", "Pepper", "Ambroxan"],
  "topNotes": ["Calabrian Bergamot", "Pepper"],
  "middleNotes": ["Sichuan Pepper", "Lavender", "Pink Pepper"],
  "baseNotes": ["Ambroxan", "Cedar", "Labdanum"],
  "accords": ["Fresh Spicy", "Citrus", "Amber", "Aromatic"],
  "longevity": "8-10 hours",
  "projection": "Strong",
  "season": "Fall/Winter"
}